# Autogenerated wrapper script for OpenImageIO_jll for x86_64-w64-mingw32-cxx11
export iconvert, idiff, igrep, iinfo, libOpenImageIO, libOpenImageIO_Util, maketx, oiiotool, testtex

using FFMPEG_jll
using FreeType2_jll
using Giflib_jll
using JpegTurbo_jll
using Libtiff_jll
using OpenEXR_jll
using OpenJpeg_jll
using Zlib_jll
using boost_jll
using libpng_jll
using libwebp_jll
using pugixml_jll
JLLWrappers.@generate_wrapper_header("OpenImageIO")
JLLWrappers.@declare_library_product(libOpenImageIO, "libOpenImageIO.dll")
JLLWrappers.@declare_library_product(libOpenImageIO_Util, "libOpenImageIO_Util.dll")
JLLWrappers.@declare_executable_product(iconvert)
JLLWrappers.@declare_executable_product(idiff)
JLLWrappers.@declare_executable_product(igrep)
JLLWrappers.@declare_executable_product(iinfo)
JLLWrappers.@declare_executable_product(maketx)
JLLWrappers.@declare_executable_product(oiiotool)
JLLWrappers.@declare_executable_product(testtex)
function __init__()
    JLLWrappers.@generate_init_header(FFMPEG_jll, FreeType2_jll, Giflib_jll, JpegTurbo_jll, Libtiff_jll, OpenEXR_jll, OpenJpeg_jll, Zlib_jll, boost_jll, libpng_jll, libwebp_jll, pugixml_jll)
    JLLWrappers.@init_library_product(
        libOpenImageIO,
        "bin\\libOpenImageIO.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOpenImageIO_Util,
        "bin\\libOpenImageIO_Util.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        iconvert,
        "bin\\iconvert.exe",
    )

    JLLWrappers.@init_executable_product(
        idiff,
        "bin\\idiff.exe",
    )

    JLLWrappers.@init_executable_product(
        igrep,
        "bin\\igrep.exe",
    )

    JLLWrappers.@init_executable_product(
        iinfo,
        "bin\\iinfo.exe",
    )

    JLLWrappers.@init_executable_product(
        maketx,
        "bin\\maketx.exe",
    )

    JLLWrappers.@init_executable_product(
        oiiotool,
        "bin\\oiiotool.exe",
    )

    JLLWrappers.@init_executable_product(
        testtex,
        "bin\\testtex.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
